### ISSUE TITLE
Issue when exporting

### ISSUE THREAD

**Issue by waz86** [tml1024/Blender2MSFS2#15]
Hi, I'm pretty new to this so forgive me if I'm making a dumb mistake, but when I try to export, I get this error:

```
Python: Traceback (most recent call last):
  File "C:\Users\waz\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Blender2MSFS2\exporter\__init__.py", line 598, in execute
    return gltf2_blender_export.save_ext_gltf(context, export_settings)
  File "C:\Users\waz\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_export.py", line 58, in save_ext_gltf
    json, buffer = __export_ext_gltf(export_settings)
  File "C:\Users\waz\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_export.py", line 81, in __export_ext_gltf
    __gather_ext_gltf(exporter, export_settings)
  File "C:\Users\waz\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_export.py", line 90, in __gather_ext_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Users\waz\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_gather.py", line 38, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "C:\Users\waz\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Users\waz\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_gather.py", line 55, in __gather_scene
    for _blender_object in [obj for obj in blender_scene.objects if obj.proxy is None]:
  File "C:\Users\waz\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_gather.py", line 55, in <listcomp>
    for _blender_object in [obj for obj in blender_scene.objects if obj.proxy is None]:
AttributeError: 'Object' object has no attribute 'proxy'

```

**Comment by JamalOne1** [comment]
Hi! Sorry that I'cant help. That this is my first experiece to. So now we are two having this issue. Hope someone can help us.

**Comment by JamalOne1** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\janer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Blender2MSFS2\exporter\__init__.py", line 598, in execute
    return gltf2_blender_export.save_ext_gltf(context, export_settings)
  File "C:\Users\janer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_export.py", line 58, in save_ext_gltf
    json, buffer = __export_ext_gltf(export_settings)
  File "C:\Users\janer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_export.py", line 81, in __export_ext_gltf
    __gather_ext_gltf(exporter, export_settings)
  File "C:\Users\janer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_export.py", line 90, in __gather_ext_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Users\janer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_gather.py", line 38, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "C:\Users\janer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Users\janer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_gather.py", line 55, in __gather_scene
    for _blender_object in [obj for obj in blender_scene.objects if obj.proxy is None]:
  File "C:\Users\janer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Blender2MSFS2\exporter\exp\gltf2_blender_gather.py", line 55, in <listcomp>
    for _blender_object in [obj for obj in blender_scene.objects if obj.proxy is None]:
AttributeError: 'Object' object has no attribute 'proxy'

**Comment by btronquo** [comment]
What's your blender version ?

**Comment by JamalOne1** [comment]
3.3

**Comment by btronquo** [comment]
3.3 is still an alpha.. 
Blender2MSFS is not available with the latests versions of blender
You can either use blender 2.8 (LTS) with this plugin or use the official Asobo plugin (wip) here : https://github.com/AsoboStudio/glTF-Blender-IO-MSFS (with blender 3.1 / 3.2)

**Comment by NicoVisagie** [comment]
I also have the same error. Just download Bklender V3.0.0 and install that for you with this exporter and it is fixed. Download older blender versions here: https://download.blender.org/release/.
